### ISSUE TITLE
Current Level Indicator for Upgrades, Items, and Powerups

### ISSUE THREAD

**Issue by hparcells** [WeAreDevs/MaterialClicker#12]
# Feature Request

## Is your feature request related to a problem? Please describe.
Can't easily know the current level.

## Describe the solution you'd like.
Adding text next to the upgrade title in the shop list saying, "Current Level: x".

## Describe alternatives you've considered.
None.

## Additional Notes.
![image](https://user-images.githubusercontent.com/40444294/43742395-c3f259b8-999f-11e8-8b96-b833a92a155b.png)

**Comment by ImDaveead** [comment]
This is already a thing, but #11 is causing this problem of it not updating. I do like the level bar as an alternative and that might be a better idea.
